package com.linjia.web.query;

import java.util.Date;

import com.linjia.base.query.Query;

public class FavouriteProductQuery extends Query{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_favourite_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_favourite_product.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_favourite_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_favourite_product.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_favourite_product.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;
    
    private String mallCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_favourite_product.id
     *
     * @return the value of b_favourite_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_favourite_product.id
     *
     * @param id the value for b_favourite_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_favourite_product.user_id
     *
     * @return the value of b_favourite_product.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_favourite_product.user_id
     *
     * @param userId the value for b_favourite_product.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_favourite_product.product_id
     *
     * @return the value of b_favourite_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_favourite_product.product_id
     *
     * @param productId the value for b_favourite_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_favourite_product.p_code
     *
     * @return the value of b_favourite_product.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_favourite_product.p_code
     *
     * @param pCode the value for b_favourite_product.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_favourite_product.cre_date
     *
     * @return the value of b_favourite_product.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_favourite_product.cre_date
     *
     * @param creDate the value for b_favourite_product.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

	public String getMallCode() {
		return mallCode;
	}

	public void setMallCode(String mallCode) {
		this.mallCode = mallCode;
	}
    
    
}