package com.linjia.web.query;

import java.util.Date;
import java.util.List;

import com.linjia.base.query.Query;

public class UserCardCouponQuery extends Query{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.card_coupon_id
     *
     * @mbggenerated
     */
    private Integer cardCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.receive_time
     *
     * @mbggenerated
     */
    private Date receiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.use_start_time
     *
     * @mbggenerated
     */
    private Date useStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.use_end_time
     *
     * @mbggenerated
     */
    private Date useEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.use_status
     *
     * @mbggenerated
     */
    private Integer useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_card_coupon.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.id
     *
     * @return the value of b_user_card_coupon.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.id
     *
     * @param id the value for b_user_card_coupon.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.user_id
     *
     * @return the value of b_user_card_coupon.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.user_id
     *
     * @param userId the value for b_user_card_coupon.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.card_coupon_id
     *
     * @return the value of b_user_card_coupon.card_coupon_id
     *
     * @mbggenerated
     */
    public Integer getCardCouponId() {
        return cardCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.card_coupon_id
     *
     * @param cardCouponId the value for b_user_card_coupon.card_coupon_id
     *
     * @mbggenerated
     */
    public void setCardCouponId(Integer cardCouponId) {
        this.cardCouponId = cardCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.receive_time
     *
     * @return the value of b_user_card_coupon.receive_time
     *
     * @mbggenerated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.receive_time
     *
     * @param receiveTime the value for b_user_card_coupon.receive_time
     *
     * @mbggenerated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.use_start_time
     *
     * @return the value of b_user_card_coupon.use_start_time
     *
     * @mbggenerated
     */
    public Date getUseStartTime() {
        return useStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.use_start_time
     *
     * @param useStartTime the value for b_user_card_coupon.use_start_time
     *
     * @mbggenerated
     */
    public void setUseStartTime(Date useStartTime) {
        this.useStartTime = useStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.use_end_time
     *
     * @return the value of b_user_card_coupon.use_end_time
     *
     * @mbggenerated
     */
    public Date getUseEndTime() {
        return useEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.use_end_time
     *
     * @param useEndTime the value for b_user_card_coupon.use_end_time
     *
     * @mbggenerated
     */
    public void setUseEndTime(Date useEndTime) {
        this.useEndTime = useEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.use_status
     *
     * @return the value of b_user_card_coupon.use_status
     *
     * @mbggenerated
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.use_status
     *
     * @param useStatus the value for b_user_card_coupon.use_status
     *
     * @mbggenerated
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_card_coupon.deleted
     *
     * @return the value of b_user_card_coupon.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user_card_coupon.deleted
     *
     * @param deleted the value for b_user_card_coupon.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    
    private Date nowTime;
    
    private Date updateDate;
    
    private String mallCode;
    
    /** 商品Id列表* */
    private List<String> productCodes;

	public Date getNowTime() {
		return nowTime;
	}

	public void setNowTime(Date nowTime) {
		this.nowTime = nowTime;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getMallCode() {
		return mallCode;
	}

	public void setMallCode(String mallCode) {
		this.mallCode = mallCode;
	}

	public List<String> getProductCodes() {
		return productCodes;
	}

	public void setProductCodes(List<String> productCodes) {
		this.productCodes = productCodes;
	}

    
	
}