package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class AccountcashChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_accountcash_change.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_accountcash_change.action
     *
     * @mbggenerated
     */
    private Integer action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_accountcash_change.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_accountcash_change.occur
     *
     * @mbggenerated
     */
    private BigDecimal occur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_accountcash_change.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_accountcash_change.id
     *
     * @return the value of b_accountcash_change.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_accountcash_change.id
     *
     * @param id the value for b_accountcash_change.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_accountcash_change.action
     *
     * @return the value of b_accountcash_change.action
     *
     * @mbggenerated
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_accountcash_change.action
     *
     * @param action the value for b_accountcash_change.action
     *
     * @mbggenerated
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_accountcash_change.user_id
     *
     * @return the value of b_accountcash_change.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_accountcash_change.user_id
     *
     * @param userId the value for b_accountcash_change.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_accountcash_change.occur
     *
     * @return the value of b_accountcash_change.occur
     *
     * @mbggenerated
     */
    public BigDecimal getOccur() {
        return occur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_accountcash_change.occur
     *
     * @param occur the value for b_accountcash_change.occur
     *
     * @mbggenerated
     */
    public void setOccur(BigDecimal occur) {
        this.occur = occur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_accountcash_change.cre_date
     *
     * @return the value of b_accountcash_change.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_accountcash_change.cre_date
     *
     * @param creDate the value for b_accountcash_change.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
    
    private boolean deleted;

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
    
    
}