package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class CardCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.card_id
     *
     * @mbggenerated
     */
    private Long cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.timeStamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.card_name
     *
     * @mbggenerated
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.card_pic
     *
     * @mbggenerated
     */
    private String cardPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.card_type
     *
     * @mbggenerated
     */
    private Integer cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.provide_type
     *
     * @mbggenerated
     */
    private Integer provideType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.code_type
     *
     * @mbggenerated
     */
    private Integer codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.time_type
     *
     * @mbggenerated
     */
    private Integer timeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.use_start_time
     *
     * @mbggenerated
     */
    private Date useStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.use_end_time
     *
     * @mbggenerated
     */
    private Date useEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.valid_day
     *
     * @mbggenerated
     */
    private Integer validDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.valid_begin_day
     *
     * @mbggenerated
     */
    private Integer validBeginDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.total_num
     *
     * @mbggenerated
     */
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.wncode
     *
     * @mbggenerated
     */
    private String wncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.limit_money
     *
     * @mbggenerated
     */
    private BigDecimal limitMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.inter_note
     *
     * @mbggenerated
     */
    private String interNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.privilege_description
     *
     * @mbggenerated
     */
    private String privilegeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.template_pic
     *
     * @mbggenerated
     */
    private String templatePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.code_flg
     *
     * @mbggenerated
     */
    private Boolean codeFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.create_code_stat
     *
     * @mbggenerated
     */
    private Integer createCodeStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.getNum
     *
     * @mbggenerated
     */
    private Integer getnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.useNum
     *
     * @mbggenerated
     */
    private Integer usenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.postID
     *
     * @mbggenerated
     */
    private Integer postid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.salePrice
     *
     * @mbggenerated
     */
    private BigDecimal saleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.unitID
     *
     * @mbggenerated
     */
    private Integer unitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.unitName
     *
     * @mbggenerated
     */
    private String unitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.goodsSelectorID
     *
     * @mbggenerated
     */
    private Integer goodsselectorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.userSelectorID
     *
     * @mbggenerated
     */
    private Integer userselectorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.useFlg
     *
     * @mbggenerated
     */
    private Boolean useflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.is_generate
     *
     * @mbggenerated
     */
    private Integer isGenerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.repeat_count
     *
     * @mbggenerated
     */
    private Integer repeatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.reset_count
     *
     * @mbggenerated
     */
    private Integer resetCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.mall_support_type
     *
     * @mbggenerated
     */
    private Integer mallSupportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.merchant_support_type
     *
     * @mbggenerated
     */
    private Integer merchantSupportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.can_give_friend
     *
     * @mbggenerated
     */
    private Integer canGiveFriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.is_mobile_verify
     *
     * @mbggenerated
     */
    private Integer isMobileVerify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.verify_type
     *
     * @mbggenerated
     */
    private Integer verifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.merchantID
     *
     * @mbggenerated
     */
    private Integer merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.merchantName
     *
     * @mbggenerated
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.merchant_flg
     *
     * @mbggenerated
     */
    private Integer merchantFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.activity_flg
     *
     * @mbggenerated
     */
    private Integer activityFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.b2c_usable
     *
     * @mbggenerated
     */
    private Integer b2cUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.wap_usable
     *
     * @mbggenerated
     */
    private Integer wapUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.app_usable
     *
     * @mbggenerated
     */
    private Integer appUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.pad_usable
     *
     * @mbggenerated
     */
    private Integer padUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.card_audit_status
     *
     * @mbggenerated
     */
    private Integer cardAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.mallareaID
     *
     * @mbggenerated
     */
    private Integer mallareaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.mallID
     *
     * @mbggenerated
     */
    private Integer mallid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.mallName
     *
     * @mbggenerated
     */
    private String mallname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.review_id
     *
     * @mbggenerated
     */
    private Integer reviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.review_no_through_reason
     *
     * @mbggenerated
     */
    private String reviewNoThroughReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.external_no
     *
     * @mbggenerated
     */
    private String externalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.is_to_wechat
     *
     * @mbggenerated
     */
    private Integer isToWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.to_wechat_status
     *
     * @mbggenerated
     */
    private Integer toWechatStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.is_to_alipay
     *
     * @mbggenerated
     */
    private Integer isToAlipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.to_alipay_status
     *
     * @mbggenerated
     */
    private Integer toAlipayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.support_condition
     *
     * @mbggenerated
     */
    private Integer supportCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.selectorID_json
     *
     * @mbggenerated
     */
    private String selectoridJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_coupon.template_code
     *
     * @mbggenerated
     */
    private String templateCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.card_id
     *
     * @return the value of card_coupon.card_id
     *
     * @mbggenerated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.card_id
     *
     * @param cardId the value for card_coupon.card_id
     *
     * @mbggenerated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.timeStamp
     *
     * @return the value of card_coupon.timeStamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.timeStamp
     *
     * @param timestamp the value for card_coupon.timeStamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.creator
     *
     * @return the value of card_coupon.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.creator
     *
     * @param creator the value for card_coupon.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.createTime
     *
     * @return the value of card_coupon.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.createTime
     *
     * @param createtime the value for card_coupon.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.card_name
     *
     * @return the value of card_coupon.card_name
     *
     * @mbggenerated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.card_name
     *
     * @param cardName the value for card_coupon.card_name
     *
     * @mbggenerated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.card_pic
     *
     * @return the value of card_coupon.card_pic
     *
     * @mbggenerated
     */
    public String getCardPic() {
        return cardPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.card_pic
     *
     * @param cardPic the value for card_coupon.card_pic
     *
     * @mbggenerated
     */
    public void setCardPic(String cardPic) {
        this.cardPic = cardPic == null ? null : cardPic.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.start_time
     *
     * @return the value of card_coupon.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.start_time
     *
     * @param startTime the value for card_coupon.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.end_time
     *
     * @return the value of card_coupon.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.end_time
     *
     * @param endTime the value for card_coupon.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.use_start_time
     *
     * @return the value of card_coupon.use_start_time
     *
     * @mbggenerated
     */
    public Date getUseStartTime() {
        return useStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.use_start_time
     *
     * @param useStartTime the value for card_coupon.use_start_time
     *
     * @mbggenerated
     */
    public void setUseStartTime(Date useStartTime) {
        this.useStartTime = useStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.use_end_time
     *
     * @return the value of card_coupon.use_end_time
     *
     * @mbggenerated
     */
    public Date getUseEndTime() {
        return useEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.use_end_time
     *
     * @param useEndTime the value for card_coupon.use_end_time
     *
     * @mbggenerated
     */
    public void setUseEndTime(Date useEndTime) {
        this.useEndTime = useEndTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.total_num
     *
     * @return the value of card_coupon.total_num
     *
     * @mbggenerated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.total_num
     *
     * @param totalNum the value for card_coupon.total_num
     *
     * @mbggenerated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.discount
     *
     * @return the value of card_coupon.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.discount
     *
     * @param discount the value for card_coupon.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.wncode
     *
     * @return the value of card_coupon.wncode
     *
     * @mbggenerated
     */
    public String getWncode() {
        return wncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.wncode
     *
     * @param wncode the value for card_coupon.wncode
     *
     * @mbggenerated
     */
    public void setWncode(String wncode) {
        this.wncode = wncode == null ? null : wncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.amount
     *
     * @return the value of card_coupon.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.amount
     *
     * @param amount the value for card_coupon.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.limit_money
     *
     * @return the value of card_coupon.limit_money
     *
     * @mbggenerated
     */
    public BigDecimal getLimitMoney() {
        return limitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.limit_money
     *
     * @param limitMoney the value for card_coupon.limit_money
     *
     * @mbggenerated
     */
    public void setLimitMoney(BigDecimal limitMoney) {
        this.limitMoney = limitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.inter_note
     *
     * @return the value of card_coupon.inter_note
     *
     * @mbggenerated
     */
    public String getInterNote() {
        return interNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.inter_note
     *
     * @param interNote the value for card_coupon.inter_note
     *
     * @mbggenerated
     */
    public void setInterNote(String interNote) {
        this.interNote = interNote == null ? null : interNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.privilege_description
     *
     * @return the value of card_coupon.privilege_description
     *
     * @mbggenerated
     */
    public String getPrivilegeDescription() {
        return privilegeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.privilege_description
     *
     * @param privilegeDescription the value for card_coupon.privilege_description
     *
     * @mbggenerated
     */
    public void setPrivilegeDescription(String privilegeDescription) {
        this.privilegeDescription = privilegeDescription == null ? null : privilegeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.template_pic
     *
     * @return the value of card_coupon.template_pic
     *
     * @mbggenerated
     */
    public String getTemplatePic() {
        return templatePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.template_pic
     *
     * @param templatePic the value for card_coupon.template_pic
     *
     * @mbggenerated
     */
    public void setTemplatePic(String templatePic) {
        this.templatePic = templatePic == null ? null : templatePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.code_flg
     *
     * @return the value of card_coupon.code_flg
     *
     * @mbggenerated
     */
    public Boolean getCodeFlg() {
        return codeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.code_flg
     *
     * @param codeFlg the value for card_coupon.code_flg
     *
     * @mbggenerated
     */
    public void setCodeFlg(Boolean codeFlg) {
        this.codeFlg = codeFlg;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.getNum
     *
     * @return the value of card_coupon.getNum
     *
     * @mbggenerated
     */
    public Integer getGetnum() {
        return getnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.getNum
     *
     * @param getnum the value for card_coupon.getNum
     *
     * @mbggenerated
     */
    public void setGetnum(Integer getnum) {
        this.getnum = getnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.useNum
     *
     * @return the value of card_coupon.useNum
     *
     * @mbggenerated
     */
    public Integer getUsenum() {
        return usenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.useNum
     *
     * @param usenum the value for card_coupon.useNum
     *
     * @mbggenerated
     */
    public void setUsenum(Integer usenum) {
        this.usenum = usenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.postID
     *
     * @return the value of card_coupon.postID
     *
     * @mbggenerated
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.postID
     *
     * @param postid the value for card_coupon.postID
     *
     * @mbggenerated
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.salePrice
     *
     * @return the value of card_coupon.salePrice
     *
     * @mbggenerated
     */
    public BigDecimal getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.salePrice
     *
     * @param saleprice the value for card_coupon.salePrice
     *
     * @mbggenerated
     */
    public void setSaleprice(BigDecimal saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.unitID
     *
     * @return the value of card_coupon.unitID
     *
     * @mbggenerated
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.unitID
     *
     * @param unitid the value for card_coupon.unitID
     *
     * @mbggenerated
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.unitName
     *
     * @return the value of card_coupon.unitName
     *
     * @mbggenerated
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.unitName
     *
     * @param unitname the value for card_coupon.unitName
     *
     * @mbggenerated
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname == null ? null : unitname.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.useFlg
     *
     * @return the value of card_coupon.useFlg
     *
     * @mbggenerated
     */
    public Boolean getUseflg() {
        return useflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.useFlg
     *
     * @param useflg the value for card_coupon.useFlg
     *
     * @mbggenerated
     */
    public void setUseflg(Boolean useflg) {
        this.useflg = useflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.description
     *
     * @return the value of card_coupon.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.description
     *
     * @param description the value for card_coupon.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.repeat_count
     *
     * @return the value of card_coupon.repeat_count
     *
     * @mbggenerated
     */
    public Integer getRepeatCount() {
        return repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.repeat_count
     *
     * @param repeatCount the value for card_coupon.repeat_count
     *
     * @mbggenerated
     */
    public void setRepeatCount(Integer repeatCount) {
        this.repeatCount = repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.reset_count
     *
     * @return the value of card_coupon.reset_count
     *
     * @mbggenerated
     */
    public Integer getResetCount() {
        return resetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.reset_count
     *
     * @param resetCount the value for card_coupon.reset_count
     *
     * @mbggenerated
     */
    public void setResetCount(Integer resetCount) {
        this.resetCount = resetCount;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.merchantID
     *
     * @return the value of card_coupon.merchantID
     *
     * @mbggenerated
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.merchantID
     *
     * @param merchantid the value for card_coupon.merchantID
     *
     * @mbggenerated
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.merchantName
     *
     * @return the value of card_coupon.merchantName
     *
     * @mbggenerated
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.merchantName
     *
     * @param merchantname the value for card_coupon.merchantName
     *
     * @mbggenerated
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.mallareaID
     *
     * @return the value of card_coupon.mallareaID
     *
     * @mbggenerated
     */
    public Integer getMallareaid() {
        return mallareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.mallareaID
     *
     * @param mallareaid the value for card_coupon.mallareaID
     *
     * @mbggenerated
     */
    public void setMallareaid(Integer mallareaid) {
        this.mallareaid = mallareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.mallID
     *
     * @return the value of card_coupon.mallID
     *
     * @mbggenerated
     */
    public Integer getMallid() {
        return mallid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.mallID
     *
     * @param mallid the value for card_coupon.mallID
     *
     * @mbggenerated
     */
    public void setMallid(Integer mallid) {
        this.mallid = mallid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.mallName
     *
     * @return the value of card_coupon.mallName
     *
     * @mbggenerated
     */
    public String getMallname() {
        return mallname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.mallName
     *
     * @param mallname the value for card_coupon.mallName
     *
     * @mbggenerated
     */
    public void setMallname(String mallname) {
        this.mallname = mallname == null ? null : mallname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.review_id
     *
     * @return the value of card_coupon.review_id
     *
     * @mbggenerated
     */
    public Integer getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.review_id
     *
     * @param reviewId the value for card_coupon.review_id
     *
     * @mbggenerated
     */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.review_no_through_reason
     *
     * @return the value of card_coupon.review_no_through_reason
     *
     * @mbggenerated
     */
    public String getReviewNoThroughReason() {
        return reviewNoThroughReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.review_no_through_reason
     *
     * @param reviewNoThroughReason the value for card_coupon.review_no_through_reason
     *
     * @mbggenerated
     */
    public void setReviewNoThroughReason(String reviewNoThroughReason) {
        this.reviewNoThroughReason = reviewNoThroughReason == null ? null : reviewNoThroughReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.external_no
     *
     * @return the value of card_coupon.external_no
     *
     * @mbggenerated
     */
    public String getExternalNo() {
        return externalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.external_no
     *
     * @param externalNo the value for card_coupon.external_no
     *
     * @mbggenerated
     */
    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo == null ? null : externalNo.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.selectorID_json
     *
     * @return the value of card_coupon.selectorID_json
     *
     * @mbggenerated
     */
    public String getSelectoridJson() {
        return selectoridJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.selectorID_json
     *
     * @param selectoridJson the value for card_coupon.selectorID_json
     *
     * @mbggenerated
     */
    public void setSelectoridJson(String selectoridJson) {
        this.selectoridJson = selectoridJson == null ? null : selectoridJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_coupon.template_code
     *
     * @return the value of card_coupon.template_code
     *
     * @mbggenerated
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_coupon.template_code
     *
     * @param templateCode the value for card_coupon.template_code
     *
     * @mbggenerated
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode == null ? null : templateCode.trim();
    }
    
    private Long userCardCouponId;
    
    /** 门店code(多个门店code已逗号分隔) * */
    private String mallCode;
    
    /** 领券时间 * */
    private Date receiveTime;
    
    /** 卡券使用状态:0未使用；1已使用 * */
    private Integer useStatus;
    
    /** 卡券在订单中能否使用:0能使用；1不能使用 * */
    private int canUseFlag = 0;
    
    /** 领券人user_id * */
    private String cardCouponUserId;
    
    /** 商品券展示图片 * */
    private String imagePath;

	public Long getUserCardCouponId() {
		return userCardCouponId;
	}

	public void setUserCardCouponId(Long userCardCouponId) {
		this.userCardCouponId = userCardCouponId;
	}

	public String getCardCouponUserId() {
		return cardCouponUserId;
	}

	public void setCardCouponUserId(String cardCouponUserId) {
		this.cardCouponUserId = cardCouponUserId;
	}

	public Date getReceiveTime() {
		return receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	public Integer getUseStatus() {
		return useStatus;
	}

	public void setUseStatus(Integer useStatus) {
		this.useStatus = useStatus;
	}

	public Integer getCardType() {
		return cardType;
	}

	public void setCardType(Integer cardType) {
		this.cardType = cardType;
	}

	public Integer getProvideType() {
		return provideType;
	}

	public void setProvideType(Integer provideType) {
		this.provideType = provideType;
	}

	public Integer getCodeType() {
		return codeType;
	}

	public void setCodeType(Integer codeType) {
		this.codeType = codeType;
	}

	public Integer getTimeType() {
		return timeType;
	}

	public void setTimeType(Integer timeType) {
		this.timeType = timeType;
	}

	public Integer getValidDay() {
		return validDay;
	}

	public void setValidDay(Integer validDay) {
		this.validDay = validDay;
	}

	public Integer getValidBeginDay() {
		return validBeginDay;
	}

	public void setValidBeginDay(Integer validBeginDay) {
		this.validBeginDay = validBeginDay;
	}

	public Integer getCreateCodeStat() {
		return createCodeStat;
	}

	public void setCreateCodeStat(Integer createCodeStat) {
		this.createCodeStat = createCodeStat;
	}

	public Integer getGoodsselectorid() {
		return goodsselectorid;
	}

	public void setGoodsselectorid(Integer goodsselectorid) {
		this.goodsselectorid = goodsselectorid;
	}

	public Integer getUserselectorid() {
		return userselectorid;
	}

	public void setUserselectorid(Integer userselectorid) {
		this.userselectorid = userselectorid;
	}

	public Integer getIsGenerate() {
		return isGenerate;
	}

	public void setIsGenerate(Integer isGenerate) {
		this.isGenerate = isGenerate;
	}

	public Integer getMallSupportType() {
		return mallSupportType;
	}

	public void setMallSupportType(Integer mallSupportType) {
		this.mallSupportType = mallSupportType;
	}

	public Integer getMerchantSupportType() {
		return merchantSupportType;
	}

	public void setMerchantSupportType(Integer merchantSupportType) {
		this.merchantSupportType = merchantSupportType;
	}

	public Integer getCanGiveFriend() {
		return canGiveFriend;
	}

	public void setCanGiveFriend(Integer canGiveFriend) {
		this.canGiveFriend = canGiveFriend;
	}

	public Integer getIsMobileVerify() {
		return isMobileVerify;
	}

	public void setIsMobileVerify(Integer isMobileVerify) {
		this.isMobileVerify = isMobileVerify;
	}

	public Integer getVerifyType() {
		return verifyType;
	}

	public void setVerifyType(Integer verifyType) {
		this.verifyType = verifyType;
	}

	public Integer getMerchantFlg() {
		return merchantFlg;
	}

	public void setMerchantFlg(Integer merchantFlg) {
		this.merchantFlg = merchantFlg;
	}

	public Integer getActivityFlg() {
		return activityFlg;
	}

	public void setActivityFlg(Integer activityFlg) {
		this.activityFlg = activityFlg;
	}

	public Integer getB2cUsable() {
		return b2cUsable;
	}

	public void setB2cUsable(Integer b2cUsable) {
		this.b2cUsable = b2cUsable;
	}

	public Integer getWapUsable() {
		return wapUsable;
	}

	public void setWapUsable(Integer wapUsable) {
		this.wapUsable = wapUsable;
	}

	public Integer getAppUsable() {
		return appUsable;
	}

	public void setAppUsable(Integer appUsable) {
		this.appUsable = appUsable;
	}

	public Integer getPadUsable() {
		return padUsable;
	}

	public void setPadUsable(Integer padUsable) {
		this.padUsable = padUsable;
	}

	public Integer getCardAuditStatus() {
		return cardAuditStatus;
	}

	public void setCardAuditStatus(Integer cardAuditStatus) {
		this.cardAuditStatus = cardAuditStatus;
	}

	public Integer getIsToWechat() {
		return isToWechat;
	}

	public void setIsToWechat(Integer isToWechat) {
		this.isToWechat = isToWechat;
	}

	public Integer getToWechatStatus() {
		return toWechatStatus;
	}

	public void setToWechatStatus(Integer toWechatStatus) {
		this.toWechatStatus = toWechatStatus;
	}

	public Integer getIsToAlipay() {
		return isToAlipay;
	}

	public void setIsToAlipay(Integer isToAlipay) {
		this.isToAlipay = isToAlipay;
	}

	public Integer getToAlipayStatus() {
		return toAlipayStatus;
	}

	public void setToAlipayStatus(Integer toAlipayStatus) {
		this.toAlipayStatus = toAlipayStatus;
	}

	public Integer getSupportCondition() {
		return supportCondition;
	}

	public void setSupportCondition(Integer supportCondition) {
		this.supportCondition = supportCondition;
	}

	public String getMallCode() {
		return mallCode;
	}

	public void setMallCode(String mallCode) {
		this.mallCode = mallCode;
	}

	public int getCanUseFlag() {
		return canUseFlag;
	}

	public void setCanUseFlag(int canUseFlag) {
		this.canUseFlag = canUseFlag;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
    
    
}