package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class DesaccountPayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.accountAccessCode
     *
     * @mbggenerated
     */
    private String accountaccesscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.accountAccessType
     *
     * @mbggenerated
     */
    private Integer accountaccesstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.orgCode
     *
     * @mbggenerated
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.occur
     *
     * @mbggenerated
     */
    private BigDecimal occur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.tranStatus
     *
     * @mbggenerated
     */
    private Integer transtatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_desaccount_pay_record.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.id
     *
     * @return the value of b_desaccount_pay_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.id
     *
     * @param id the value for b_desaccount_pay_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.accountAccessCode
     *
     * @return the value of b_desaccount_pay_record.accountAccessCode
     *
     * @mbggenerated
     */
    public String getAccountaccesscode() {
        return accountaccesscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.accountAccessCode
     *
     * @param accountaccesscode the value for b_desaccount_pay_record.accountAccessCode
     *
     * @mbggenerated
     */
    public void setAccountaccesscode(String accountaccesscode) {
        this.accountaccesscode = accountaccesscode == null ? null : accountaccesscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.accountAccessType
     *
     * @return the value of b_desaccount_pay_record.accountAccessType
     *
     * @mbggenerated
     */
    public Integer getAccountaccesstype() {
        return accountaccesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.accountAccessType
     *
     * @param accountaccesstype the value for b_desaccount_pay_record.accountAccessType
     *
     * @mbggenerated
     */
    public void setAccountaccesstype(Integer accountaccesstype) {
        this.accountaccesstype = accountaccesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.orgCode
     *
     * @return the value of b_desaccount_pay_record.orgCode
     *
     * @mbggenerated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.orgCode
     *
     * @param orgcode the value for b_desaccount_pay_record.orgCode
     *
     * @mbggenerated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.occur
     *
     * @return the value of b_desaccount_pay_record.occur
     *
     * @mbggenerated
     */
    public BigDecimal getOccur() {
        return occur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.occur
     *
     * @param occur the value for b_desaccount_pay_record.occur
     *
     * @mbggenerated
     */
    public void setOccur(BigDecimal occur) {
        this.occur = occur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.group_id
     *
     * @return the value of b_desaccount_pay_record.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.group_id
     *
     * @param groupId the value for b_desaccount_pay_record.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.tranStatus
     *
     * @return the value of b_desaccount_pay_record.tranStatus
     *
     * @mbggenerated
     */
    public Integer getTranstatus() {
        return transtatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.tranStatus
     *
     * @param transtatus the value for b_desaccount_pay_record.tranStatus
     *
     * @mbggenerated
     */
    public void setTranstatus(Integer transtatus) {
        this.transtatus = transtatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_desaccount_pay_record.cre_date
     *
     * @return the value of b_desaccount_pay_record.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_desaccount_pay_record.cre_date
     *
     * @param creDate the value for b_desaccount_pay_record.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
    
    private Long xid;

	public Long getXid() {
		return xid;
	}

	public void setXid(Long xid) {
		this.xid = xid;
	}
    
    
}