package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class HotsellProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.base_id
     *
     * @mbggenerated
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.p_price
     *
     * @mbggenerated
     */
    private BigDecimal pPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.p_send_type
     *
     * @mbggenerated
     */
    private Integer pSendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_hotsell_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.id
     *
     * @return the value of b_hotsell_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.id
     *
     * @param id the value for b_hotsell_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.base_id
     *
     * @return the value of b_hotsell_product.base_id
     *
     * @mbggenerated
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.base_id
     *
     * @param baseId the value for b_hotsell_product.base_id
     *
     * @mbggenerated
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.product_id
     *
     * @return the value of b_hotsell_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.product_id
     *
     * @param productId the value for b_hotsell_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.p_code
     *
     * @return the value of b_hotsell_product.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.p_code
     *
     * @param pCode the value for b_hotsell_product.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.p_name
     *
     * @return the value of b_hotsell_product.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.p_name
     *
     * @param pName the value for b_hotsell_product.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.p_price
     *
     * @return the value of b_hotsell_product.p_price
     *
     * @mbggenerated
     */
    public BigDecimal getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.p_price
     *
     * @param pPrice the value for b_hotsell_product.p_price
     *
     * @mbggenerated
     */
    public void setpPrice(BigDecimal pPrice) {
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.p_send_type
     *
     * @return the value of b_hotsell_product.p_send_type
     *
     * @mbggenerated
     */
    public Integer getpSendType() {
        return pSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.p_send_type
     *
     * @param pSendType the value for b_hotsell_product.p_send_type
     *
     * @mbggenerated
     */
    public void setpSendType(Integer pSendType) {
        this.pSendType = pSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.create_time
     *
     * @return the value of b_hotsell_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.create_time
     *
     * @param createTime the value for b_hotsell_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_hotsell_product.update_time
     *
     * @return the value of b_hotsell_product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_hotsell_product.update_time
     *
     * @param updateTime the value for b_hotsell_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    /**
	 * 商品的库存的状态
	 * (0:正常；1：库存不足)
	 */
	private int qtyStatus;
	
	private String imagePath;
	
	private String detailPath;
	
	private BigDecimal salePrice;
	
	private BigDecimal marketPrice;

	/** 商品折扣* */
	private Double discount;
	
	/** 商品标签* */
	private String promotionLabel;

	public int getQtyStatus() {
		return qtyStatus;
	}

	public void setQtyStatus(int qtyStatus) {
		this.qtyStatus = qtyStatus;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getDetailPath() {
		return detailPath;
	}

	public void setDetailPath(String detailPath) {
		this.detailPath = detailPath;
	}

	public BigDecimal getSalePrice() {
		return salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	public BigDecimal getMarketPrice() {
		return marketPrice;
	}

	public void setMarketPrice(BigDecimal marketPrice) {
		this.marketPrice = marketPrice;
	}

	public Double getDiscount() {
		return discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public String getPromotionLabel() {
		return promotionLabel;
	}

	public void setPromotionLabel(String promotionLabel) {
		this.promotionLabel = promotionLabel;
	}
	
	
}