package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Product {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.id
	 *
	 * @mbggenerated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.p_code
	 *
	 * @mbggenerated
	 */
	private String pCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.description
	 *
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.image_path
	 *
	 * @mbggenerated
	 */
	private String imagePath;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.detail_path
	 *
	 * @mbggenerated
	 */
	private String detailPath;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.p_type
	 *
	 * @mbggenerated
	 */
	private Integer pType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.stock_type
	 *
	 * @mbggenerated
	 */
	private Integer stockType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.supplier
	 *
	 * @mbggenerated
	 */
	private String supplier;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.brand_id
	 *
	 * @mbggenerated
	 */
	private Long brandId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.brand_name
	 *
	 * @mbggenerated
	 */
	private String brandName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.p_comment
	 *
	 * @mbggenerated
	 */
	private String pComment;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.large_catagory
	 *
	 * @mbggenerated
	 */
	private Integer largeCatagoryId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.middle_catagory
	 *
	 * @mbggenerated
	 */
	private Integer middleCatagoryId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.small_catagory
	 *
	 * @mbggenerated
	 */
	private Integer smallCatagoryId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.keywords
	 *
	 * @mbggenerated
	 */
	private String keywords;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.available
	 *
	 * @mbggenerated
	 */
	private Integer available;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.sale_price
	 *
	 * @mbggenerated
	 */
	private BigDecimal salePrice;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.market_price
	 *
	 * @mbggenerated
	 */
	private BigDecimal marketPrice;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.spec_id
	 *
	 * @mbggenerated
	 */
	private Integer specId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.p_label
	 *
	 * @mbggenerated
	 */
	private String pLabel;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.qrcode_big
	 *
	 * @mbggenerated
	 */
	private String qrcodeBig;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.qrcode_middle
	 *
	 * @mbggenerated
	 */
	private String qrcodeMiddle;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.qrcode_small
	 *
	 * @mbggenerated
	 */
	private String qrcodeSmall;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.cre_date
	 *
	 * @mbggenerated
	 */
	private Date creDate;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.update_date
	 *
	 * @mbggenerated
	 */
	private Date updateDate;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.deleted
	 *
	 * @mbggenerated
	 */
	private Boolean deleted;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_product.deleted
	 *
	 * @mbggenerated
	 */
	private Integer quantity;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.id
	 *
	 * @return the value of b_product.id
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.id
	 *
	 * @param id the value for b_product.id
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.p_code
	 *
	 * @return the value of b_product.p_code
	 *
	 * @mbggenerated
	 */
	public String getpCode() {
		return pCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.p_code
	 *
	 * @param pCode the value for b_product.p_code
	 *
	 * @mbggenerated
	 */
	public void setpCode(String pCode) {
		this.pCode = pCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.name
	 *
	 * @return the value of b_product.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.name
	 *
	 * @param name the value for b_product.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.description
	 *
	 * @return the value of b_product.description
	 *
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.description
	 *
	 * @param description the value for b_product.description
	 *
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.image_path
	 *
	 * @return the value of b_product.image_path
	 *
	 * @mbggenerated
	 */
	public String getImagePath() {
		return imagePath;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.image_path
	 *
	 * @param imagePath the value for b_product.image_path
	 *
	 * @mbggenerated
	 */
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath == null ? null : imagePath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.detail_path
	 *
	 * @return the value of b_product.detail_path
	 *
	 * @mbggenerated
	 */
	public String getDetailPath() {
		return detailPath;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.detail_path
	 *
	 * @param detailPath the value for b_product.detail_path
	 *
	 * @mbggenerated
	 */
	public void setDetailPath(String detailPath) {
		this.detailPath = detailPath == null ? null : detailPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.p_type
	 *
	 * @return the value of b_product.p_type
	 *
	 * @mbggenerated
	 */
	public Integer getpType() {
		return pType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.p_type
	 *
	 * @param pType the value for b_product.p_type
	 *
	 * @mbggenerated
	 */
	public void setpType(Integer pType) {
		this.pType = pType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.stock_type
	 *
	 * @return the value of b_product.stock_type
	 *
	 * @mbggenerated
	 */
	public Integer getStockType() {
		return stockType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.stock_type
	 *
	 * @param stockType the value for b_product.stock_type
	 *
	 * @mbggenerated
	 */
	public void setStockType(Integer stockType) {
		this.stockType = stockType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.supplier
	 *
	 * @return the value of b_product.supplier
	 *
	 * @mbggenerated
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.supplier
	 *
	 * @param supplier the value for b_product.supplier
	 *
	 * @mbggenerated
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier == null ? null : supplier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.brand_id
	 *
	 * @return the value of b_product.brand_id
	 *
	 * @mbggenerated
	 */
	public Long getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.brand_id
	 *
	 * @param brandId the value for b_product.brand_id
	 *
	 * @mbggenerated
	 */
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.brand_name
	 *
	 * @return the value of b_product.brand_name
	 *
	 * @mbggenerated
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.brand_name
	 *
	 * @param brandName the value for b_product.brand_name
	 *
	 * @mbggenerated
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName == null ? null : brandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.p_comment
	 *
	 * @return the value of b_product.p_comment
	 *
	 * @mbggenerated
	 */
	public String getpComment() {
		return pComment;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.p_comment
	 *
	 * @param pComment the value for b_product.p_comment
	 *
	 * @mbggenerated
	 */
	public void setpComment(String pComment) {
		this.pComment = pComment == null ? null : pComment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.large_catagory
	 *
	 * @return the value of b_product.large_catagory
	 *
	 * @mbggenerated
	 */
	public Integer getLargeCatagoryId() {
		return largeCatagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.large_catagory
	 *
	 * @param largeCatagory the value for b_product.large_catagory
	 *
	 * @mbggenerated
	 */
	public void setLargeCatagoryId(Integer largeCatagoryId) {
		this.largeCatagoryId = largeCatagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.middle_catagory
	 *
	 * @return the value of b_product.middle_catagory
	 *
	 * @mbggenerated
	 */
	public Integer getMiddleCatagoryId() {
		return middleCatagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.middle_catagory
	 *
	 * @param middleCatagory the value for b_product.middle_catagory
	 *
	 * @mbggenerated
	 */
	public void setMiddleCatagoryId(Integer middleCatagoryId) {
		this.middleCatagoryId = middleCatagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.small_catagory
	 *
	 * @return the value of b_product.small_catagory
	 *
	 * @mbggenerated
	 */
	public Integer getSmallCatagoryId() {
		return smallCatagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.small_catagory
	 *
	 * @param smallCatagory the value for b_product.small_catagory
	 *
	 * @mbggenerated
	 */
	public void setSmallCatagoryId(Integer smallCatagoryId) {
		this.smallCatagoryId = smallCatagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.keywords
	 *
	 * @return the value of b_product.keywords
	 *
	 * @mbggenerated
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.keywords
	 *
	 * @param keywords the value for b_product.keywords
	 *
	 * @mbggenerated
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords == null ? null : keywords.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.available
	 *
	 * @return the value of b_product.available
	 *
	 * @mbggenerated
	 */
	public Integer getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.available
	 *
	 * @param available the value for b_product.available
	 *
	 * @mbggenerated
	 */
	public void setAvailable(Integer available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.sale_price
	 *
	 * @return the value of b_product.sale_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getSalePrice() {
		return salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.sale_price
	 *
	 * @param salePrice the value for b_product.sale_price
	 *
	 * @mbggenerated
	 */
	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.market_price
	 *
	 * @return the value of b_product.market_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getMarketPrice() {
		return marketPrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.market_price
	 *
	 * @param marketPrice the value for b_product.market_price
	 *
	 * @mbggenerated
	 */
	public void setMarketPrice(BigDecimal marketPrice) {
		this.marketPrice = marketPrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.spec_id
	 *
	 * @return the value of b_product.spec_id
	 *
	 * @mbggenerated
	 */
	public Integer getSpecId() {
		return specId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.spec_id
	 *
	 * @param specId the value for b_product.spec_id
	 *
	 * @mbggenerated
	 */
	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.p_label
	 *
	 * @return the value of b_product.p_label
	 *
	 * @mbggenerated
	 */
	public String getpLabel() {
		return pLabel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.p_label
	 *
	 * @param pLabel the value for b_product.p_label
	 *
	 * @mbggenerated
	 */
	public void setpLabel(String pLabel) {
		this.pLabel = pLabel == null ? null : pLabel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.qrcode_big
	 *
	 * @return the value of b_product.qrcode_big
	 *
	 * @mbggenerated
	 */
	public String getQrcodeBig() {
		return qrcodeBig;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.qrcode_big
	 *
	 * @param qrcodeBig the value for b_product.qrcode_big
	 *
	 * @mbggenerated
	 */
	public void setQrcodeBig(String qrcodeBig) {
		this.qrcodeBig = qrcodeBig == null ? null : qrcodeBig.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.qrcode_middle
	 *
	 * @return the value of b_product.qrcode_middle
	 *
	 * @mbggenerated
	 */
	public String getQrcodeMiddle() {
		return qrcodeMiddle;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.qrcode_middle
	 *
	 * @param qrcodeMiddle the value for b_product.qrcode_middle
	 *
	 * @mbggenerated
	 */
	public void setQrcodeMiddle(String qrcodeMiddle) {
		this.qrcodeMiddle = qrcodeMiddle == null ? null : qrcodeMiddle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.qrcode_small
	 *
	 * @return the value of b_product.qrcode_small
	 *
	 * @mbggenerated
	 */
	public String getQrcodeSmall() {
		return qrcodeSmall;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.qrcode_small
	 *
	 * @param qrcodeSmall the value for b_product.qrcode_small
	 *
	 * @mbggenerated
	 */
	public void setQrcodeSmall(String qrcodeSmall) {
		this.qrcodeSmall = qrcodeSmall == null ? null : qrcodeSmall.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.cre_date
	 *
	 * @return the value of b_product.cre_date
	 *
	 * @mbggenerated
	 */
	public Date getCreDate() {
		return creDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.cre_date
	 *
	 * @param creDate the value for b_product.cre_date
	 *
	 * @mbggenerated
	 */
	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.update_date
	 *
	 * @return the value of b_product.update_date
	 *
	 * @mbggenerated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.update_date
	 *
	 * @param updateDate the value for b_product.update_date
	 *
	 * @mbggenerated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_product.deleted
	 *
	 * @return the value of b_product.deleted
	 *
	 * @mbggenerated
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_product.deleted
	 *
	 * @param deleted the value for b_product.deleted
	 *
	 * @mbggenerated
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * 商品在对应门店的安全库存值
	 * 
	 */
	private int safeQuantity;
	/**
	 * 商品的库存的状态
	 * (0:正常；1：库存不足)
	 */
	private int qtyStatus;
	
	/**商品发货类型：0及时送；1次日达 * */
	private Integer pSendType;
	
	/**商品标签数组 * */
	private List<String> tagList;
	
	/** 本月销量* */
	private Integer saleNum;
	
	/** 商品关注Id* */
	private String favouriteProductId;
	
	/** 商品折扣* */
	private Double discount;
	
	/** 商品标签* */
	private String promotionLabel;
	
	public int getSafeQuantity() {
		return safeQuantity;
	}

	public void setSafeQuantity(int safeQuantity) {
		this.safeQuantity = safeQuantity;
	}

	public int getQtyStatus() {
		return qtyStatus;
	}

	public void setQtyStatus(int qtyStatus) {
		this.qtyStatus = qtyStatus;
	}

	public Integer getpSendType() {
		return pSendType;
	}

	public void setpSendType(Integer pSendType) {
		this.pSendType = pSendType;
	}

	public List<String> getTagList() {
		return tagList;
	}

	public void setTagList(List<String> tagList) {
		this.tagList = tagList;
	}

	public Integer getSaleNum() {
		return saleNum;
	}

	public void setSaleNum(Integer saleNum) {
		this.saleNum = saleNum;
	}

	public String getFavouriteProductId() {
		return favouriteProductId;
	}

	public void setFavouriteProductId(String favouriteProductId) {
		this.favouriteProductId = favouriteProductId;
	}

	public Double getDiscount() {
		return discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public String getPromotionLabel() {
		return promotionLabel;
	}

	public void setPromotionLabel(String promotionLabel) {
		this.promotionLabel = promotionLabel;
	}

}