package com.linjia.web.model;


/**
 * 区划model
 * @author lixinling
 * 2016年9月6日 上午11:02:11
 */
public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_address.user_id
     *
     * @mbggenerated
     */
    private String name;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

    
    
}