package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ShoppingCar {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_shopping_car.id
	 *
	 * @mbggenerated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_shopping_car.product_id
	 *
	 * @mbggenerated
	 */
	private Long productId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_shopping_car.p_code
	 *
	 * @mbggenerated
	 */
	private String pCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_shopping_car.user_id
	 *
	 * @mbggenerated
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_shopping_car.quantity
	 *
	 * @mbggenerated
	 */
	private Integer quantity;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_shopping_car.cre_date
	 *
	 * @mbggenerated
	 */
	private Date creDate;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_shopping_car.id
	 *
	 * @return the value of b_shopping_car.id
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_shopping_car.id
	 *
	 * @param id the value for b_shopping_car.id
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_shopping_car.product_id
	 *
	 * @return the value of b_shopping_car.product_id
	 *
	 * @mbggenerated
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_shopping_car.product_id
	 *
	 * @param productId the value for b_shopping_car.product_id
	 *
	 * @mbggenerated
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_shopping_car.p_code
	 *
	 * @return the value of b_shopping_car.p_code
	 *
	 * @mbggenerated
	 */
	public String getpCode() {
		return pCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_shopping_car.p_code
	 *
	 * @param pCode the value for b_shopping_car.p_code
	 *
	 * @mbggenerated
	 */
	public void setpCode(String pCode) {
		this.pCode = pCode == null ? null : pCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_shopping_car.user_id
	 *
	 * @return the value of b_shopping_car.user_id
	 *
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_shopping_car.user_id
	 *
	 * @param userId the value for b_shopping_car.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_shopping_car.quantity
	 *
	 * @return the value of b_shopping_car.quantity
	 *
	 * @mbggenerated
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_shopping_car.quantity
	 *
	 * @param quantity the value for b_shopping_car.quantity
	 *
	 * @mbggenerated
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_shopping_car.cre_date
	 *
	 * @return the value of b_shopping_car.cre_date
	 *
	 * @mbggenerated
	 */
	public Date getCreDate() {
		return creDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_shopping_car.cre_date
	 *
	 * @param creDate the value for b_shopping_car.cre_date
	 *
	 * @mbggenerated
	 */
	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	/**
	 * 购物车每条记录的价格
	 */
	private BigDecimal itemPrice;

	/**
	 * 购物车每条记录的状态
	 * (0:正常；1：库存不足)
	 */
	private int itemStatus;

	/**
	 * 商品名
	 */
	private String pName;

	/**
	 * 商品发货类型：0及时送；1次日达
	 */
	private int pSendType;

	/**
	 * 秒杀活动时的购买数量
	 */
	private int miaoshaoQty;

	/**
	 * 秒杀活动时的商品表id
	 */
	private Long miaoshaoActiveProductId;

	/**
	 * 尾货清仓活动时的id
	 */
	private Long tailGoodsClearId;

	/**
	 * 商品图片
	 */
	private String imagePath;

	/**
	 * 参与的活动类型：1,满减；2，商品折扣；3第二件半价；4，加钱换购；5，免运费；6，会员促销;7,秒杀；8,尾货清仓
	 */
	private Integer activityType;

	/**
	 * 活动表的主键id
	 */
	private Long activityId;
	
	/**
	 * 活动表的主键id(加钱换购活动)
	 */
	private Long tradeActivityId;
	
	/**
	 * 活动的名称(加钱换购活动)
	 */
	private String tradeActivityName;
	
	/**
	 * 加钱换购商品表的主键id
	 */
	private String tradeProductIds;
	
	/**
	 * 加钱换购时的购物车父记录id
	 */
	private Long parentId;
	
	/**
	 * 换购商品列表
	 */
	private List<ActivityTradeProduct> activityTradeProductList;

	public BigDecimal getItemPrice() {
		return itemPrice;
	}

	public void setItemPrice(BigDecimal itemPrice) {
		this.itemPrice = itemPrice;
	}

	public int getItemStatus() {
		return itemStatus;
	}

	public void setItemStatus(int itemStatus) {
		this.itemStatus = itemStatus;
	}

	public String getpName() {
		return pName;
	}

	public void setpName(String pName) {
		this.pName = pName;
	}

	public int getpSendType() {
		return pSendType;
	}

	public void setpSendType(int pSendType) {
		this.pSendType = pSendType;
	}

	public int getMiaoshaoQty() {
		return miaoshaoQty;
	}

	public void setMiaoshaoQty(int miaoshaoQty) {
		this.miaoshaoQty = miaoshaoQty;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public Long getMiaoshaoActiveProductId() {
		return miaoshaoActiveProductId;
	}

	public void setMiaoshaoActiveProductId(Long miaoshaoActiveProductId) {
		this.miaoshaoActiveProductId = miaoshaoActiveProductId;
	}

	public Long getTailGoodsClearId() {
		return tailGoodsClearId;
	}

	public void setTailGoodsClearId(Long tailGoodsClearId) {
		this.tailGoodsClearId = tailGoodsClearId;
	}

	public Integer getActivityType() {
		return activityType;
	}

	public void setActivityType(Integer activityType) {
		this.activityType = activityType;
	}

	public Long getActivityId() {
		return activityId;
	}

	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	public List<ActivityTradeProduct> getActivityTradeProductList() {
		return activityTradeProductList;
	}

	public void setActivityTradeProductList(List<ActivityTradeProduct> activityTradeProductList) {
		this.activityTradeProductList = activityTradeProductList;
	}

	/** 商品优惠前总价格* */
	private BigDecimal itemTotalPrice;
	/** 单件商品价格* */
	private BigDecimal productPrice;
	/** 商品优惠金额* */
	private BigDecimal discountAmount;
	/** 整单优惠分摊金额* */
	private BigDecimal apportedDiscountAmount;
	/** 预约购买活动id* */
	private Integer prepareActivityId;
	/** 加钱换购时父商品的pcode* */
	private String parentPCode;
	/** 商品换购价格* */
	private BigDecimal pTradePrice;
	/** 是否是商品券商品：0否，1是* */
	private Integer isSpq =0;

	public BigDecimal getProductPrice() {
		return productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	public BigDecimal getDiscountAmount() {
		return discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	public BigDecimal getApportedDiscountAmount() {
		return apportedDiscountAmount;
	}

	public void setApportedDiscountAmount(BigDecimal apportedDiscountAmount) {
		this.apportedDiscountAmount = apportedDiscountAmount;
	}

	public BigDecimal getItemTotalPrice() {
		return itemTotalPrice;
	}

	public void setItemTotalPrice(BigDecimal itemTotalPrice) {
		this.itemTotalPrice = itemTotalPrice;
	}

	public Integer getPrepareActivityId() {
		return prepareActivityId;
	}

	public void setPrepareActivityId(Integer prepareActivityId) {
		this.prepareActivityId = prepareActivityId;
	}

	public String getParentPCode() {
		return parentPCode;
	}

	public void setParentPCode(String parentPCode) {
		this.parentPCode = parentPCode;
	}

	public BigDecimal getpTradePrice() {
		return pTradePrice;
	}

	public void setpTradePrice(BigDecimal pTradePrice) {
		this.pTradePrice = pTradePrice;
	}

	public Integer getIsSpq() {
		return isSpq;
	}

	public void setIsSpq(Integer isSpq) {
		this.isSpq = isSpq;
	}

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public String getTradeProductIds() {
		return tradeProductIds;
	}

	public void setTradeProductIds(String tradeProductIds) {
		this.tradeProductIds = tradeProductIds;
	}

	public Long getTradeActivityId() {
		return tradeActivityId;
	}

	public void setTradeActivityId(Long tradeActivityId) {
		this.tradeActivityId = tradeActivityId;
	}

	public String getTradeActivityName() {
		return tradeActivityName;
	}

	public void setTradeActivityName(String tradeActivityName) {
		this.tradeActivityName = tradeActivityName;
	}

	

}